config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get 'home/index'

  authenticate :user, ->(u) { u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")

  scope module: :back_office do
    resources :resumes_replicas
    resource :resume, only: %i[update edit]

    resources :resumes, only: [] do
      member do
        resources :experiences, only: [:create]
      end
    end

    resources :experiences, only: [:destroy]
  end


  scope module: :front_office do
    get "/:username/:resume_id", to: "resumes#show", as: :public_resume
  end

  devise_scope :user do
    authenticated do
      root to: 'back_office/resumes_replicas#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'home#index'
    end
  end
end

app/controllers/back_office/experiences_controller.rb
# frozen_string_literal: true

module BackOffice
  class ExperiencesController < BackOfficeController
    before_action :set_resume, only: %i[create]

    def create
      @experience = @resume.experiences.create(title: 'New experience...')

      respond_to do |format|
        format.turbo_stream do
          if @experience.valid?
            render turbo_stream: turbo_stream.update(@resume, partial: 'back_office/resumes/form',
                                                              locals: { resume: @resume })
          else
            render turbo_stream: turbo_stream.update(:model_errors, partial: 'layouts/shared/model_errors',
                                                                    locals: { model: @experience })
          end
        end
        format.html do
          redirect_to edit_resume_path
        end
      end
    end

    def destroy
      @experience = current_user.experiences.find(params[:id])
      @experience.destroy

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.remove(@experience)
        end
      end
    end

    private

    def set_resume
      @resume = current_user.resumes.find(params[:id])
    end
  end
end

app/controllers/back_office/resumes_controller.rb
# frozen_string_literal: true

module BackOffice
  class ResumesController < BackOfficeController
    before_action :set_resume, only: %i[edit update]

    def edit
      return unless @is_onboarding_resume
    end

    def update
      respond_to do |format|
        if @resume.update(resume_params)
          format.html { redirect_to resume_url, notice: 'Resume was successfully updated.' }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    private

    def set_resume
      create_resume if current_user.resume.nil?

      @resume = current_user.resume
    end

    def create_resume
      @is_onboarding_resume = true
      current_user.create_resume(**ONBOARDING_RESUME)
    end

    def resume_params
      params.require(:resume).permit(:title,
                                     :about,
                                     :developer_since,
                                     :location,
                                     :meeting_url,
                                     :video_url,
                                     :slug,
                                     user_attributes: [
                                      :id,
                                      :avatar_image,
                                      :first_name,
                                      :last_name,
                                      :username
                                     ],
                                     experiences_attributes: %i[
                                       id
                                       description
                                       ended_at
                                       started_at
                                       title
                                       skills
                                     ])
    end
  end
end

app/controllers/back_office/resumes_replicas_controller.rb
# frozen_string_literal: true

module BackOffice
  class ResumesReplicasController < BackOfficeController
    before_action :set_resume_replica, only: %i[show edit update destroy]

    def index
      @resumes_replicas = current_user.resumes_replicas.all
      @resume = current_user.resume
    end

    def show; end

    def new
      @resumes_replica = current_user.resume.dup
      @resumes_replica = @resumes_replica.becomes!(Resumes::Replica)
      @resumes_replica.recruter_image_url = ''

      return unless current_user.resumes_replicas.count.zero?
      ONBOARDING_RESUME_REPLICA.keys.each do |key|
        @resumes_replica.public_send("#{key}=", ONBOARDING_RESUME_REPLICA[key])
      end
      @resumes_replica.recruter_image_url = "#{Rails.env.production? ? 'https://freelance-resume.rolandsoftwares.com/' : 'http://localhost:3000/'}elon_musk.jpeg"
    end

    def edit; end

    def create
      @resume = current_user.resume
      @resumes_replica = @resume.dup
      @resume.experiences.map { |experience| @resumes_replica.experiences << experience.dup }
      @resumes_replica.becomes!(Resumes::Replica)
      @resumes_replica.update(resume_params)

      respond_to do |format|
        if @resumes_replica.valid?
          if @resumes_replica.not_started?
            ResumesReplicas::GenerateJob.perform_async(@resumes_replica.id)
            @resumes_replica.processing!
          end
          format.html { redirect_to resumes_replica_path(@resumes_replica), notice: 'Resume was successfully created.' }
        else
          format.turbo_stream { render turbo_stream: turbo_stream.update(:model_errors, partial: 'layouts/shared/model_errors', locals: { model: @resumes_replica }) }
        end
      end
    end

    def update
      respond_to do |format|
        if @resume_replica.update(resume_params)
          format.html { redirect_to resumes_replica_path(@resume_replica), notice: 'Resume was successfully updated.' }
        else
          format.turbo_stream { render turbo_stream: turbo_stream.update(:model_errors, partial: 'layouts/shared/model_errors', locals: { model: @resume_replica }) }
        end
      end
    end

    def destroy
      if @resume_replica.destroy
        redirect_to resumes_replicas_path, notice: "Resume deleted"
      else
        render :show
      end
    end

    private

    def set_resume_replica
      @resume_replica = current_user.resumes_replicas.find(params[:id])
    end

    def resume_params
      params.require(:resumes_replica).permit(:title,
        :about,
        :recruter_email,
        :recruter_full_name,
        :company_name,
        :recruter_image_url,
        :avatar_image,
        :location,
        :developer_since,
        :meeting_url,
        :video_url,
        :job_description,
        experiences_attributes: %i[
                                       id
                                       description
                                       ended_at
                                       started_at
                                       title
                                       skills
                                     ]
      )
    end
  end
end

app/controllers/back_office_controller.rb
# frozen_string_literal: true

class BackOfficeController < ApplicationController
  before_action :authenticate_user!
  before_action :save_ip

  private

  def save_ip
    @device = current_user.devices.where(remote_ip: request.remote_ip, user_agent: request.user_agent)&.first
    current_user.devices.create(remote_ip: request.remote_ip, user_agent: request.user_agent) if @device.nil?
  end
end

app/helpers/back_office/resumes_helper.rb
# frozen_string_literal: true

module BackOffice
  module ResumesHelper
  end
end

app/views/back_office/resumes_replicas/_form.html.erb
<%= render partial: 'back_office/resumes/form', locals: { resume: resumes_replica } %>
<% form_with(model: resumes_replica) do |form| %>
  <%= render "layouts/shared/model_errors", model: resumes_replica %>
  <div class="space-y-6 py-6">
    <div class="flex items-center">
      <%= image_tag resumes_replica.avatar_image.persisted? ? url_for(resumes_replica.avatar_image) : resumes_replica.recruter_image_url, class: "w-20 h-20 rounded-full border-2 border-slate-400 mr-6" %>
      <div class="">
        <%= form.label :avatar_image, class: "w-full mb-1 font-bold" %>
        <%= form.file_field :avatar_image, class: "w-full border border-gray-400 rounded" %>
        <%= form.hidden_field :recruter_image_url, value: resumes_replica.recruter_image_url %>
      </div>
    </div>
    <div class="flex flex-col">
      <%= form.label :company_name, class: "w-full mb-1 font-bold" %>
      <%= form.text_field :company_name, class: "w-full border border-gray-400 rounded" %>
    </div>
    <div class="flex flex-col">
      <%= form.label :recruter_full_name, class: "w-full mb-1 font-bold" %>
      <%= form.text_field :recruter_full_name, class: "w-full border border-gray-400 rounded" %>
    </div>
    <div class="flex flex-col">
      <%= form.label :recruter_email, class: "w-full mb-1 font-bold" %>
      <%= form.text_field :recruter_email, class: "w-full border border-gray-400 rounded" %>
    </div>
    <div class="flex flex-col">
      <%= form.label :title, class: "w-full mb-1 font-bold" %>
      <%= form.text_field :title, class: "w-full border border-gray-400 rounded" %>
    </div>
    <div class="flex flex-col">
      <%= form.label :job_description, class: "mb-1 font-bold" %>
      <%= form.text_area :job_description, class: "border border-gray-400 rounded", rows: "5" %>
    </div>
  </div>
  <div class="flex justify-start">
    <%= form.submit "Generate replica", class: "rounded py-2 px-4 bg-blue-600 text-white inline-block font-medium cursor-pointer", data: { turbo_frame: "_top" } %>
  </div>
<% end %>

app/views/back_office/resumes_replicas/_resume.html.erb
<li class="relative flex justify-between gap-x-6 px-4 py-5 hover:bg-gray-50 sm:px-6 lg:px-8">
  <div class="flex min-w-0 gap-x-4">
    <img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="<%= resume.avatar_image.persisted? ? url_for(resume.avatar_image) : resume.recruter_image_url %>" alt="">
    <div class="min-w-0 flex-auto">
      <p class="text-sm font-semibold leading-6 text-gray-900">
        <a href="<%= resumes_replica_path(resume) %>">
          <span class="absolute inset-x-0 -top-px bottom-0"></span>
          <%= resume.recruter_full_name %>
        </a>
      </p>
      <p class="mt-1 flex text-xs leading-5 text-gray-500">
        <% if resume.recruter_email.present? %>
          <a href="mailto:<%= resume.recruter_email %>" class="relative truncate hover:underline"><%= resume.recruter_email %></a>
        <% else %>
          <p class="relative truncate hover:underline text-gray-300 italic">email not present</p>
        <% end %>
      </p>
    </div>
  </div>
  <div class="flex shrink-0 items-center gap-x-4">
    <div class="hidden sm:flex sm:flex-col sm:items-end">
      <p class="text-sm leading-6 text-gray-900"><%= resume.title %></p>
      <%= render "status", status: resume.status %>
    </div>
    <svg class="h-5 w-5 flex-none text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
      <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
    </svg>
  </div>
</li>

app/views/back_office/resumes_replicas/_status.html.erb
<% if status == "not_started" %>
  <div class="mt-1 flex items-center gap-x-1.5">
    <div class="flex-none rounded-full bg-gray-500/20 p-1">
      <div class="h-1.5 w-1.5 rounded-full bg-gray-500"></div>
    </div>
    <p class="text-xs leading-5 text-gray-500">Not enhanced</p>
  </div>
<% elsif status == "processing" %>
  <div class="mt-1 flex items-center gap-x-1.5">
    <div class="flex-none rounded-full bg-orange-500/20 p-1">
      <div class="h-1.5 w-1.5 rounded-full bg-orange-500"></div>
    </div>
    <p class="text-xs leading-5 text-orange-500">Processing</p>
  </div>
<% elsif status == "done" %>
  <div class="mt-1 flex items-center gap-x-1.5">
    <div class="flex-none rounded-full bg-emerald-500/20 p-1">
      <div class="h-1.5 w-1.5 rounded-full bg-emerald-500"></div>
    </div>
    <p class="text-xs leading-5 text-gray-500">Ready</p>
  </div>
<% else %>
  <div class="mt-1 flex items-center gap-x-1.5">
    <div class="flex-none rounded-full bg-red-600/20 p-1">
      <div class="h-1.5 w-1.5 rounded-full bg-red-600"></div>
    </div>
    <p class="text-xs leading-5 text-red-600">Error</p>
  </div>
<% end %>

app/views/back_office/resumes_replicas/edit.html.erb
<div class="flex flex-col md:flex-row justify-between items-center mb-6">
  <h1 class="font-bold text-4xl">Edit replica</h1>
  <%= link_to "Back to resumes", resumes_replicas_path, class: "mt-3 md:mt-0 rounded py-2 px-4 bg-gray-100 inline-block font-medium border-2 border-black" %>
</div>
<hr>
<%= render partial: 'form', locals: { resumes_replica: @resume_replica } %>

app/views/back_office/resumes_replicas/index.html.erb
<div class="w-full">
  <div id="resumes" class="min-w-full mb-6">
    <% if @resume.present? && (@resumes_replicas.count == 0) %>
      <%= render "layouts/shared/notice", message: 'STEP 2: Click "Generate resume replica"' %>
    <% elsif @resume.nil? %>
      <%= render "layouts/shared/notice", message: "STEP 1: Edit your original resume first" %>
    <% end %>
  </div>
  <div class="flex flex-col md:flex-row justify-between items-center">
    <h1 class="font-bold text-4xl">Resumes</h1>
    <div class="flex flex-col md:flex-row justify-center md:justify-end text-center">
      <% if @resume.present? %>
        <%= link_to "Generate resume replica", new_resumes_replica_path, class: "rounded py-2 px-4 border-2 border-blue-600 text-blue-600 block font-medium md:mr-3 mt-3 md:mt-0" %>
      <% end %>
      <%= link_to "Edit original resumer", edit_resume_path, class: "mt-3 md:mt-0 rounded py-2 px-4 bg-blue-600 border-2 border-blue-600 text-white block font-medium" %>
    </div>
  </div>
  <% if @resume.present? && (@resumes_replicas.count > 0) %>
    <hr class="mt-6">
    <ul role="list" class="divide-y divide-gray-200">
      <%= render partial: "resume", collection: @resumes_replicas %>
    </ul>
  <% end %>
</div>

app/views/back_office/resumes_replicas/new.html.erb
<% if current_user.resumes_replicas.count == 0 %>
  <div class="mb-6 space-y-3">
    <%= render "layouts/shared/notice", message: "In this example, you are applying to SpaceX. 😎" %>
    <%= render "layouts/shared/notice", message: "Once happy with the data, scroll down." %>
    <%= render "layouts/shared/notice", message: "Click on 'Create replica'." %>
  </div>
<% end %>
<div class="flex flex-col md:flex-row justify-between items-center mb-6">
  <h1 class="font-bold text-4xl">Generate replica</h1>
  <%= link_to "Back to resumes", resumes_replicas_path, class: "mt-3 md:mt-0 rounded py-2 px-4 bg-gray-100 inline-block font-medium border-2 border-black" %>
</div>
<hr>
<%= render "form", resumes_replica: @resumes_replica %>

app/views/back_office/resumes_replicas/show.html.erb
<%= turbo_stream_from @resume_replica %>
<div id="<%= dom_id(@resume_replica) %>">
  <%= render "back_office/resumes_replicas/templates/toptal", user: current_user, resume: @resume_replica, show_back_office_actions: true %>
</div>