config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get 'home/index'

  authenticate :user, ->(u) { u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")

  scope module: :back_office do
    resources :resumes_replicas
    resource :resume, only: %i[update edit]

    resources :resumes, only: [] do
      member do
        resources :experiences, only: [:create]
      end
    end

    resources :experiences, only: [:destroy]
  end


  scope module: :front_office do
    get "/:username/:resume_id", to: "resumes#show", as: :public_resume
  end

  devise_scope :user do
    authenticated do
      root to: 'back_office/resumes_replicas#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'home#index'
    end
  end
end

app/models/resume.rb
# frozen_string_literal: true

class Resume < ApplicationRecord
  belongs_to :user

  has_many :experiences, class_name: Resumes::Experience.to_s, dependent: :destroy
  has_many :views, class_name: Resumes::View.to_s, dependent: :destroy

  has_one_attached :avatar_image
  enum status: { not_started: 0, processing: 1, done: 2, failed: 3 }

  accepts_nested_attributes_for :experiences, reject_if: :all_blank
  accepts_nested_attributes_for :user, update_only: true

  validates :title, presence: true
  validates :about, presence: true
  validates :location, presence: true
  validates :developer_since, presence: true
  validates :job_description, presence: true, if: -> { type == Resumes::Replica.to_s }
  validates :slug, format: { with: /\A[0-9a-zA-Z\-\_]+\z/, message: "Only allows letters, numbers and _ -" }, if: -> () { self.slug.present? }


  validate :minimum_experiences_count

  def recruter_image_url
    super.blank? ? 'https://static.licdn.com/aero-v1/sc/h/9c8pery4andzj6ohjkjp54ma2' : super
  end

  private

  def minimum_experiences_count
    return unless experiences.count.zero? && persisted?

    errors.add(:base, 'Should have at least one experience')
  end
end

# == Schema Information
#
# Table name: resumes
#
#  id                    :uuid             not null, primary key
#  about                 :text
#  company_name          :string
#  developer_since       :datetime
#  job_description       :text
#  location              :string
#  meeting_url           :string
#  recruter_email        :string
#  recruter_full_name    :string
#  recruter_image_url    :string
#  recruter_linkedin_url :string
#  slug                  :string
#  status                :integer          default(0)
#  title                 :string
#  type                  :string
#  video_url             :string
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  user_id               :uuid
#
# Indexes
#
#  index_resumes_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id) ON DELETE => cascade
#

app/models/resumes.rb
# frozen_string_literal: true

module Resumes
  def self.table_name_prefix
    'resumes_'
  end
end

app/models/resumes/experience.rb
# frozen_string_literal: true

module Resumes
  class Experience < ApplicationRecord
    Resumes::Experience::MAX_EXPERIENCES = 4
    belongs_to :resume

    validate :resume_count

    private

    def resume_count
      return unless id.nil? && (resume.experiences.count >= Resumes::Experience::MAX_EXPERIENCES)

      errors.add(:base, "Only #{Resumes::Experience::MAX_EXPERIENCES} are allowed.")
    end
  end
end

# == Schema Information
#
# Table name: resumes_experiences
#
#  id          :uuid             not null, primary key
#  description :text
#  ended_at    :datetime
#  skills      :text
#  started_at  :datetime
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  resume_id   :uuid
#
# Indexes
#
#  index_resumes_experiences_on_resume_id  (resume_id)
#
# Foreign Keys
#
#  fk_rails_...  (resume_id => resumes.id) ON DELETE => cascade
#

app/models/resumes/replica.rb
# frozen_string_literal: true

module Resumes
  class Replica < Resume
    belongs_to :user
  end
end

# == Schema Information
#
# Table name: resumes
#
#  id                    :uuid             not null, primary key
#  about                 :text
#  company_name          :string
#  developer_since       :datetime
#  job_description       :text
#  location              :string
#  meeting_url           :string
#  recruter_email        :string
#  recruter_full_name    :string
#  recruter_image_url    :string
#  recruter_linkedin_url :string
#  slug                  :string
#  status                :integer          default("not_started")
#  title                 :string
#  type                  :string
#  video_url             :string
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  user_id               :uuid
#
# Indexes
#
#  index_resumes_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id) ON DELETE => cascade
#

app/models/resumes/view.rb
class Resumes::View < ApplicationRecord
  belongs_to :resume

  after_create :send_view_email

  private
    def send_view_email
      Resumes::ViewMailer.create(self).deliver_later
    end
end

# == Schema Information
#
# Table name: resumes_views
#
#  id         :uuid             not null, primary key
#  remote_ip  :string
#  user_agent :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  resume_id  :uuid             not null
#
# Indexes
#
#  index_resumes_views_on_resume_id  (resume_id)
#
# Foreign Keys
#
#  fk_rails_...  (resume_id => resumes.id) ON DELETE => cascade
#

app/controllers/back_office/experiences_controller.rb
# frozen_string_literal: true

module BackOffice
  class ExperiencesController < BackOfficeController
    before_action :set_resume, only: %i[create]

    def create
      @experience = @resume.experiences.create(title: 'New experience...')

      respond_to do |format|
        format.turbo_stream do
          if @experience.valid?
            render turbo_stream: turbo_stream.update(@resume, partial: 'back_office/resumes/form',
                                                              locals: { resume: @resume })
          else
            render turbo_stream: turbo_stream.update(:model_errors, partial: 'layouts/shared/model_errors',
                                                                    locals: { model: @experience })
          end
        end
        format.html do
          redirect_to edit_resume_path
        end
      end
    end

    def destroy
      @experience = current_user.experiences.find(params[:id])
      @experience.destroy

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.remove(@experience)
        end
      end
    end

    private

    def set_resume
      @resume = current_user.resumes.find(params[:id])
    end
  end
end

app/controllers/back_office/resumes_controller.rb
# frozen_string_literal: true

module BackOffice
  class ResumesController < BackOfficeController
    before_action :set_resume, only: %i[edit update]

    def edit
      return unless @is_onboarding_resume
    end

    def update
      respond_to do |format|
        if @resume.update(resume_params)
          format.html { redirect_to resume_url, notice: 'Resume was successfully updated.' }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    private

    def set_resume
      create_resume if current_user.resume.nil?

      @resume = current_user.resume
    end

    def create_resume
      @is_onboarding_resume = true
      current_user.create_resume(**ONBOARDING_RESUME)
    end

    def resume_params
      params.require(:resume).permit(:title,
                                     :about,
                                     :developer_since,
                                     :location,
                                     :meeting_url,
                                     :video_url,
                                     :slug,
                                     user_attributes: [
                                      :id,
                                      :avatar_image,
                                      :first_name,
                                      :last_name,
                                      :username
                                     ],
                                     experiences_attributes: %i[
                                       id
                                       description
                                       ended_at
                                       started_at
                                       title
                                       skills
                                     ])
    end
  end
end

app/controllers/back_office/resumes_replicas_controller.rb
# frozen_string_literal: true

module BackOffice
  class ResumesReplicasController < BackOfficeController
    before_action :set_resume_replica, only: %i[show edit update destroy]

    def index
      @resumes_replicas = current_user.resumes_replicas.all
      @resume = current_user.resume
    end

    def show; end

    def new
      @resumes_replica = current_user.resume.dup
      @resumes_replica = @resumes_replica.becomes!(Resumes::Replica)
      @resumes_replica.recruter_image_url = ''

      return unless current_user.resumes_replicas.count.zero?
      ONBOARDING_RESUME_REPLICA.keys.each do |key|
        @resumes_replica.public_send("#{key}=", ONBOARDING_RESUME_REPLICA[key])
      end
      @resumes_replica.recruter_image_url = "#{Rails.env.production? ? 'https://freelance-resume.rolandsoftwares.com/' : 'http://localhost:3000/'}elon_musk.jpeg"
    end

    def edit; end

    def create
      @resume = current_user.resume
      @resumes_replica = @resume.dup
      @resume.experiences.map { |experience| @resumes_replica.experiences << experience.dup }
      @resumes_replica.becomes!(Resumes::Replica)
      @resumes_replica.update(resume_params)

      respond_to do |format|
        if @resumes_replica.valid?
          if @resumes_replica.not_started?
            ResumesReplicas::GenerateJob.perform_async(@resumes_replica.id)
            @resumes_replica.processing!
          end
          format.html { redirect_to resumes_replica_path(@resumes_replica), notice: 'Resume was successfully created.' }
        else
          format.turbo_stream { render turbo_stream: turbo_stream.update(:model_errors, partial: 'layouts/shared/model_errors', locals: { model: @resumes_replica }) }
        end
      end
    end

    def update
      respond_to do |format|
        if @resume_replica.update(resume_params)
          format.html { redirect_to resumes_replica_path(@resume_replica), notice: 'Resume was successfully updated.' }
        else
          format.turbo_stream { render turbo_stream: turbo_stream.update(:model_errors, partial: 'layouts/shared/model_errors', locals: { model: @resume_replica }) }
        end
      end
    end

    def destroy
      if @resume_replica.destroy
        redirect_to resumes_replicas_path, notice: "Resume deleted"
      else
        render :show
      end
    end

    private

    def set_resume_replica
      @resume_replica = current_user.resumes_replicas.find(params[:id])
    end

    def resume_params
      params.require(:resumes_replica).permit(:title,
        :about,
        :recruter_email,
        :recruter_full_name,
        :company_name,
        :recruter_image_url,
        :avatar_image,
        :location,
        :developer_since,
        :meeting_url,
        :video_url,
        :job_description,
        experiences_attributes: %i[
                                       id
                                       description
                                       ended_at
                                       started_at
                                       title
                                       skills
                                     ]
      )
    end
  end
end

app/controllers/back_office_controller.rb
# frozen_string_literal: true

class BackOfficeController < ApplicationController
  before_action :authenticate_user!
  before_action :save_ip

  private

  def save_ip
    @device = current_user.devices.where(remote_ip: request.remote_ip, user_agent: request.user_agent)&.first
    current_user.devices.create(remote_ip: request.remote_ip, user_agent: request.user_agent) if @device.nil?
  end
end

app/controllers/front_office/resumes_controller.rb
class FrontOffice::ResumesController < FrontOfficeController
  before_action :redirect_bots

  def show
    @resume = Resume.includes(:user).where(users: {username: params[:username]}, resumes: {id: params[:resume_id]})&.first
    raise AbstractController::ActionNotFound.new("not found") if @resume.nil?
    @user = @resume.user

    if @user.devices.where(remote_ip: request.remote_ip, user_agent: request.user_agent).count == 0
      @resume.views.create(remote_ip: request.remote_ip, user_agent: request.user_agent)
    end
  end

  private

  def redirect_bots
    if CrawlerDetect.is_crawler?(request.user_agent)
      render status: :unauthorized and return
    end
  end
end

app/helpers/back_office/resumes_helper.rb
# frozen_string_literal: true

module BackOffice
  module ResumesHelper
  end
end

app/views/back_office/resumes/_form.html.erb
<%-
  form_args = if (resume.type == Resume.to_s)
    {model: resume, url: resume_path}
  else
    {model: resume}
  end
-%>
<%= turbo_frame_tag resume do %>
  <%= form_with(**form_args) do |form| %>
    <%= render "layouts/shared/model_errors", model: resume %>
    <div class="space-y-6 py-6">
      <% if resume.type == Resume.to_s %>
        <div>
          <h1 class="font-bold text-2xl">Your information</h1>
          <p class="text-sm text-slate-400 mt-3">Used globally in every resume.</p>
        </div>
        <%= form.fields_for :user do |user_subform| %>
          <div class="grid grid-cols-2 gap-4">
            <div class="col-span-2 md:col-span-1">
              <%= image_tag avatar_image_url_for(current_user), class: "rounded-xl shadow-xl mx-auto" %>
            </div>
            <div class="col-span-2 md:col-span-1 space-y-6">
              <div class="flex flex-col">
                <%= user_subform.label :avatar_image, class: "w-full mb-1 font-bold" %>
                <%= user_subform.file_field :avatar_image, class: "w-full border border-gray-400 rounded" %>
              </div>
              <div class="flex flex-col">
                <%= user_subform.label :first_name, class: "w-full mb-1 font-bold" %>
                <%= user_subform.text_field :first_name, class: "w-full border border-gray-400 rounded" %>
              </div>
              <div class="flex flex-col">
                <%= user_subform.label :last_name, class: "w-full mb-1 font-bold" %>
                <%= user_subform.text_field :last_name, class: "w-full border border-gray-400 rounded" %>
              </div>
              <div class="flex flex-col border border-red-500 p-2 rounded bg-red-100">
                <%= user_subform.label :username, class: "w-full mb-1 font-bold" %>
                <%= user_subform.text_field :username, class: "w-full border border-red-500 border-gray-400 rounded" %>
                <p class="text-sm mt-2 text-red-500">[Danger Zone]: All previous resume will point to a 404 page.</p>
              </div>
              <hr class="md:hidden">
            </div>
          </div>
        <% end %>
      <% else %>
        <div>
          <h1 class="font-bold text-2xl">Company information</h1>
          <p class="text-sm text-slate-400 mt-3">Add customization and your resume will stand out.</p>
        </div>
        <div class="flex items-center">
          <%= image_tag resume.avatar_image.persisted? ? url_for(resume.avatar_image) : resume.recruter_image_url, class: "w-20 h-20 rounded-full border-2 border-slate-400 mr-6" %>
          <div class="">
            <%= form.label :avatar_image, class: "w-full mb-1 font-bold" %>
            <%= form.file_field :avatar_image, class: "w-full border border-gray-400 rounded" %>
            <%= form.hidden_field :recruter_image_url, value: resume.recruter_image_url %>
          </div>
        </div>
        <div class="flex flex-col">
          <%= form.label :company_name, class: "w-full mb-1 font-bold" %>
          <%= form.text_field :company_name, class: "w-full border border-gray-400 rounded" %>
        </div>
        <div class="flex flex-col">
          <%= form.label :recruter_full_name, class: "w-full mb-1 font-bold" %>
          <%= form.text_field :recruter_full_name, class: "w-full border border-gray-400 rounded" %>
        </div>
        <div class="flex flex-col">
          <%= form.label :recruter_email, class: "w-full mb-1 font-bold" %>
          <%= form.text_field :recruter_email, class: "w-full border border-gray-400 rounded" %>
        </div>
        <% unless resume.persisted? %>
          <div class="flex flex-col">
            <%= form.label :job_description, class: "mb-1 font-bold" %>
            <%= form.text_area :job_description, class: "border border-gray-400 rounded", rows: "5" %>
          </div>
        <% end %>
      <% end %>
      <% if resume.type == Resume.to_s %>
        <h1 class="font-bold text-2xl pt-3">Your original resume</h1>
      <% else %>
        <div>
          <h1 class="font-bold text-2xl pt-3">Replica resume information</h1>
          <p class="text-sm text-slate-400 mt-3">Content bellow is generated by AI.</p>
        </div>
      <% end %>
      <div class="flex flex-col">
        <%= form.label :title, class: "w-full mb-1 font-bold" %>
        <%= form.text_field :title, class: "w-full border border-gray-400 rounded" %>
      </div>
      <div class="flex flex-col">
        <%= form.label :location, class: "w-full mb-1 font-bold" %>
        <%= form.text_field :location, class: "w-full border border-gray-400 rounded" %>
      </div>
      <div class="flex flex-col">
        <%= form.label :developer_since, class: "w-full mb-1 font-bold" %>
        <%= form.date_field :developer_since, class: "w-full border border-gray-400 rounded" %>
      </div>
      <div class="flex flex-col">
        <%= form.label :meeting_url, class: "mb-1 font-bold" %>
        <%= form.text_field :meeting_url, class: "border border-gray-400 rounded" %>
        <p class="text-sm mt-2 text-slate-400">Will show a contact link with this URL.</p>
      </div>
      <div class="flex flex-col">
        <%= form.label :video_url, class: "mb-1 font-bold" %>
        <%= form.text_field :video_url, class: "border border-gray-400 rounded" %>
        <p class="text-sm mt-2 text-slate-400">The image will become clickable and will open this URL.</p>
      </div>
      <div class="flex flex-col">
        <%= form.label :about, class: "w-full mb-1 font-bold" %>
        <%= form.text_area :about, class: "w-full border border-gray-400 rounded", rows: "12" %>
      </div>
      <% if resume.persisted? %>
        <div>
          <%= form.label :experiences, class: "mb-1 font-bold" %>
          <%= form.fields_for :experiences do |experience_subform| %>
            <%= turbo_frame_tag experience_subform.object do %>
              <div class="flex flex-col space-y-4 p-3 my-3 border border-gray-400 rounded">
                <div class="flex flex-col">
                  <%= experience_subform.label :title %>
                  <%= experience_subform.text_field :title, class: "border border-gray-400 rounded" %>
                </div>
                <div class="flex flex-col">
                  <%= experience_subform.label :description %>
                  <%= experience_subform.text_area :description, class: "border border-gray-400 rounded", rows: "4" %>
                </div>
                <div class="flex flex-col">
                  <%= experience_subform.label :started_at %>
                  <%= experience_subform.date_field :started_at, class: "border border-gray-400 rounded" %>
                </div>
                <div class="flex flex-col">
                  <%= experience_subform.label :ended_at %>
                  <%= experience_subform.date_field :ended_at, class: "border border-gray-400 rounded" %>
                </div>
                <div class="flex flex-col">
                  <%= experience_subform.label :skills %>
                  <%= experience_subform.text_field :skills, class: "border border-gray-400 rounded" %>
                  <p class="text-sm mt-2 text-slate-400">Separate them with a comma, e.g: Ruby On Rails, Hotwire</p>
                </div>
                <%= link_to 'Delete', experience_path(id: experience_subform.object.id), class: "text-red-500 px-2 py-1 border-red-500 mt-3 ml-auto font-medium border-2 rounded", data: { turbo_method: :delete } %>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="flex flex-col md:flex-row justify-between">
      <%= form.submit class: "rounded py-2 px-4 bg-blue-600 text-white inline-block font-medium cursor-pointer", data: { turbo_frame: "_top" } %>
      <% if (resume.experiences == Resumes::Experience::MAX_EXPERIENCES) %>
        <%= link_to "Add experience", experiences_path(id: form.object.id), data: { turbo_method: :post }, class: "text-indigo-700 py-2 px-4 font-medium border-2 rounded border-indigo-700" %>
      <% elsif(resume.persisted?) %>
        <div class="text-gray-700 py-2 px-4 font-medium border-2 rounded border-gray-700 mt-3 md:mt-0">Only <%= Resumes::Experience::MAX_EXPERIENCES %> experiences are allowed</div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/back_office/resumes/edit.html.erb
<% if true %>
  <div class="mb-6 space-y-3">
    <%= render "layouts/shared/notice", message: "We initialized a resume example for the onboarding." %>
    <%= render "layouts/shared/notice", message: "Click 'Back to resume'" %>
  </div>
<% end %>
<div class="flex flex-col md:flex-row justify-between items-center mb-6">
  <h1 class="font-bold text-4xl">Editing resume</h1>
  <%= link_to "Back to resumes", resumes_replicas_path, class: "rounded py-2 px-4 bg-gray-100 inline-block font-medium border-2 border-black mt-3 md:mt-0" %>
</div>
<hr>
<%= render "form", resume: @resume %>

app/views/back_office/resumes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Resumes</h1>
    <%= link_to "New resume", new_resume_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="back_office_resumes" class="min-w-full">
    <%= render @resumes %>
  </div>
</div>