config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  get 'home/index'

  authenticate :user, ->(u) { u.is_admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")

  scope module: :back_office do
    resources :resumes_replicas
    resource :resume, only: %i[update edit]

    resources :resumes, only: [] do
      member do
        resources :experiences, only: [:create]
      end
    end

    resources :experiences, only: [:destroy]
  end


  scope module: :front_office do
    get "/:username/:resume_id", to: "resumes#show", as: :public_resume
  end

  devise_scope :user do
    authenticated do
      root to: 'back_office/resumes_replicas#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'home#index'
    end
  end
end

app/controllers/back_office/resumes_replicas_controller.rb
# frozen_string_literal: true

module BackOffice
  class ResumesReplicasController < BackOfficeController
    before_action :set_resume_replica, only: %i[show edit update destroy]

    def index
      @resumes_replicas = current_user.resumes_replicas.all
      @resume = current_user.resume
    end

    def show; end

    def new
      @resumes_replica = current_user.resume.dup
      @resumes_replica = @resumes_replica.becomes!(Resumes::Replica)
      @resumes_replica.recruter_image_url = ''

      return unless current_user.resumes_replicas.count.zero?
      ONBOARDING_RESUME_REPLICA.keys.each do |key|
        @resumes_replica.public_send("#{key}=", ONBOARDING_RESUME_REPLICA[key])
      end
      @resumes_replica.recruter_image_url = "#{Rails.env.production? ? 'https://freelance-resume.rolandsoftwares.com/' : 'http://localhost:3000/'}elon_musk.jpeg"
    end

    def edit; end

    def create
      @resume = current_user.resume
      @resumes_replica = @resume.dup
      @resume.experiences.map { |experience| @resumes_replica.experiences << experience.dup }
      @resumes_replica.becomes!(Resumes::Replica)
      @resumes_replica.update(resume_params)

      respond_to do |format|
        if @resumes_replica.valid?
          if @resumes_replica.not_started?
            ResumesReplicas::GenerateJob.perform_async(@resumes_replica.id)
            @resumes_replica.processing!
          end
          format.html { redirect_to resumes_replica_path(@resumes_replica), notice: 'Resume was successfully created.' }
        else
          format.turbo_stream { render turbo_stream: turbo_stream.update(:model_errors, partial: 'layouts/shared/model_errors', locals: { model: @resumes_replica }) }
        end
      end
    end

    def update
      respond_to do |format|
        if @resume_replica.update(resume_params)
          format.html { redirect_to resumes_replica_path(@resume_replica), notice: 'Resume was successfully updated.' }
        else
          format.turbo_stream { render turbo_stream: turbo_stream.update(:model_errors, partial: 'layouts/shared/model_errors', locals: { model: @resume_replica }) }
        end
      end
    end

    def destroy
      if @resume_replica.destroy
        redirect_to resumes_replicas_path, notice: "Resume deleted"
      else
        render :show
      end
    end

    private

    def set_resume_replica
      @resume_replica = current_user.resumes_replicas.find(params[:id])
    end

    def resume_params
      params.require(:resumes_replica).permit(:title,
        :about,
        :recruter_email,
        :recruter_full_name,
        :company_name,
        :recruter_image_url,
        :avatar_image,
        :location,
        :developer_since,
        :meeting_url,
        :video_url,
        :job_description,
        experiences_attributes: %i[
                                       id
                                       description
                                       ended_at
                                       started_at
                                       title
                                       skills
                                     ]
      )
    end
  end
end

app/views/back_office/resumes_replicas/templates/_toptal.html.erb
<% if (show_back_office_actions == true) && resume.processing? %>
  <div class="inset-0 backdrop-blur-md fixed z-10">
    <div class="flex flex-col max-w-md mx-auto mt-12">
      <div class="border-2 p-6 rounded-lg bg-white mx-3">
        <div class="flex items-center justify-center">
          <div class="text-xl font-bold mr-3">Processing...</div>
          <div>
            <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-black" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
              <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
              <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
          </div>
        </div>
        <hr class="my-3">
        <div class="text-xl font-bold mr-3 text-center">Your resume is being optimized by AI.</div>
        <hr class="my-3">
        <p>This will take a few seconds.</p>
        <p>You stay here OR <%= link_to "go back to your resumes.", resumes_replicas_path, class: "underline text-indigo-500" %></p>
      </div>
    </div>
  </div>
<% end %>
<% if show_back_office_actions == true %>
  <div class="w-full flex justify-end">
    <%= link_to "Back to resumes", resumes_replicas_path, class: "rounded mb-1 py-2 px-4 bg-gray-100 inline-block font-medium border-2 border-black bg-transparent" %>
  </div>
  <div class="flex justify-between flex-col mt-6 items-center space-y-4 bg-gray-200 border shadow-md border-gray-400 rounded-lg p-3">
    <p class="text-black text-xl text-center font-bold">You are currently in preview mode</p>
    <p class="text-black text-xl text-center font-bold">📈 Total Views on your resume: <%= resume.views.count %></p>
    <div class="mt-2 flex flex-col md:flex-row">
      <%= link_to public_resume_path(username: user.username, resume_id: resume.id), data:{ controller: "copy-to-clip-board" }, target: "_blank", class: "mb-1 rounded py-2 px-4 bg-gray-100 inline-block font-medium border-2 border-black bg-transparent flex items-center" do %>
        <p>Copy public link</p>
        <div class="w-5 ml-3">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M384 336H192c-8.8 0-16-7.2-16-16V64c0-8.8 7.2-16 16-16l140.1 0L400 115.9V320c0 8.8-7.2 16-16 16zM192 384H384c35.3 0 64-28.7 64-64V115.9c0-12.7-5.1-24.9-14.1-33.9L366.1 14.1c-9-9-21.2-14.1-33.9-14.1H192c-35.3 0-64 28.7-64 64V320c0 35.3 28.7 64 64 64zM64 128c-35.3 0-64 28.7-64 64V448c0 35.3 28.7 64 64 64H256c35.3 0 64-28.7 64-64V416H272v32c0 8.8-7.2 16-16 16H64c-8.8 0-16-7.2-16-16V192c0-8.8 7.2-16 16-16H96V128H64z"/></svg>
        </div>
      <% end %>
      <%= link_to "Edit", edit_resumes_replica_path(resume), class: "mb-1 mx-0 md:mx-3 rounded py-2 px-4 bg-gray-100 inline-block font-medium border-2 border-black bg-transparent" %>
      <%= link_to "Destroy", resumes_replica_path(resume), class: "mb-1 rounded py-2 px-4 text-red-500 inline-block font-medium border-2 border-red-500", data: { turbo_method: :delete, turbo_confirm: "Are you sure? The link shared will point to a 404." } %>
    </div>
  </div>
  <hr class="mt-3 mb-6">
<% end %>
<div class="relative grid grid-cols-6 gap-4 text-sm">
  <div class="col-span-6 md:col-span-2 flex flex-col items-stretch justify-start">
    <div class="sticky top-0">
      <div class="relative rounded-bl-3xl overflow-clip shadow-xl">
        <img src="<%= avatar_image_url_for(user) %>" class="z-10 w-full" alt="">
        <% if resume.video_url.present? %>
          <div class="bg-slate-400 animate-pulse inset-0 absolute -z-10"></div>
          <div class="absolute inset-0 fill-white opacity-90 bg-blend-multiply grid grid-cols-3 gap-4">
            <div class="absolute inset-0 bg-slate-700 opacity-20 bg-blend-multiply"></div>
            <div class="col-start-2 col-span-1 my-auto animate-pulse relative flex flex-col items-center">
              <p class="text-white font-bold">Watch video</p>
              <svg class="" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M0 128C0 92.7 28.7 64 64 64H320c35.3 0 64 28.7 64 64V384c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V128zM559.1 99.8c10.4 5.6 16.9 16.4 16.9 28.2V384c0 11.8-6.5 22.6-16.9 28.2s-23 5-32.9-1.6l-96-64L416 337.1V320 192 174.9l14.2-9.5 96-64c9.8-6.5 22.4-7.2 32.9-1.6z"/></svg>
            </div>
          </div>
          <a href="<%= resume.video_url %>" target="_blank" class="inset-0 absolute"></a>
        <% end %>
      </div>
      <% if resume.meeting_url.present? %>
        <div class="flex justify-between items-center mt-5 rounded border-l-4 border-green-500 py-3 pl-3">
          <div class="text-slate-600 "><%= user.first_name %> is <span class="text-green-500">available</span> for hire</div>
          <%= link_to "Contact", resume.meeting_url, target: "_blank", class: "text-center rounded py-1 px-2 border-2 bg-green-500 border-green-500 text-white font-bold" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-span-6 md:col-span-4 md:pl-12">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div class="col-span-1">
        <div class="text-2xl font-bold"><%= user.full_name %></div>
        <div class="text-slate-500 mt-2"><%= resume.title %></div>
      </div>
      <div class="col-span-1 flex justify-between items-start">
        <div>
          <div class="text-2xl font-bold"><%= resume.recruter_full_name %></div>
          <div class="text-slate-500 mt-2"><%= resume.company_name %></div>
        </div>
        <% if resume.avatar_image.persisted? || resume.recruter_image_url.end_with?("elon_musk.jpeg") %>
          <div class="my-auto">
            <img class="border-slate-400 border-2 h-12 w-12 flex-none rounded-full bg-gray-50" src="<%= resume.avatar_image.persisted? ? url_for(resume.avatar_image) : resume.recruter_image_url %>" alt="">
          </div>
        <% end %>
      </div>
    </div>
    <div class="grid grid-cols-2 gap-4 border-t border-b mt-6 ">
      <div class="col-span-1 border-r py-4">
        <div class="text-slate-500 text-sm">LOCATION</div>
        <div class="text-slate-500 font-bold"><%= resume.location %></div>
      </div>
      <div class="col-span-1 py-4 pl-6">
        <div class="text-slate-500 text-sm">DEVELOPER SINCE</div>
        <div class="text-slate-500 font-bold"><%= resume.developer_since.year %></div>
      </div>
    </div>
    <div class="my-6 text-slate-500">
      <%= simple_format(resume.about) %>
    </div>
    <div class="flex flex-wrap space-x-1">
      <% resume.experiences.map{|xp| xp.skills.split(", ")}.flatten.uniq.each do |skill| %>
        <div class="border-blue-700 border text-blue-700 px-2 py-1 rounded-full my-1">
          <%= skill %>
        </div>
      <% end %>
    </div>
    <hr class="my-6">
    <div class="text-xl font-bold mb-6">Work experience</div>
    <div class="text-slate-500">
      <% resume.experiences.each do |experience| %>
        <div class="grid grid-cols-10 gap-4">
          <div class="col-span-1 flex flex-col items-center mt-2">
            <div class="bg-blue-700 w-2 h-2 rounded-full"></div>
            <div class="h-full border-r-2 border-dashed"></div>
          </div>
          <div class="col-span-9 mb-6 space-y-4">
            <div class="flex justify-between">
              <div class="text-black font-bold"><%= experience.title %></div>
              <div class="text-slate-500 font-bold"><%= experience.started_at.year %> - <%= experience.ended_at.year %></div>
            </div>
            <div>
              <%= simple_format(experience.description) %>
            </div>
            <div>
              Technologies: <%= experience.skills %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/back_office/resumes_replicas/templates/_toptal.turbo_stream.erb
<%= turbo_stream.update resume, partial: "back_office/resumes_replicas/templates/toptal", locals: { user: user, resume: resume, show_back_office_actions: show_back_office_actions } %>